version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: "mysql_db_container"
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: 'UVUCS3520D4t4Th30ry!'
    ports:
      - 4306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
volumes:
  mysql_db_data_container: